language: c

python:
  - "3.6"

env:
    global:
    
    env:
    global:
        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test'
        - PIP_DEPENDENCIES='pytest-faulthandler pytest-mpl'
        - EVENT_TYPE='pull_request push'
        - GH_REF: github.com/cmurray-astro/gausspy.git

        # For this package-template, we include examples of Cython modules,
        # so Cython is required for testing. If your package does not include
        # Cython code, you can set CONDA_DEPENDENCIES=''
        - CONDA_DEPENDENCIES='numpy scipy h5py matplotlib'
        # - CONDA_DEPENDENCIES_DOC='sphinx-astropy sip<4.19 Cython scipy h5py matplotlib pytables hdf5 dust_extinction'
        
    matrix:
        # Make sure that egg_info works without dependencies
        #- PYTHON_VERSION=2.7 SETUP_CMD='egg_info'
        #- PYTHON_VERSION=3.5 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.6 SETUP_CMD='egg_info'
        #- PYTHON_VERSION=3.7 SETUP_CMD='egg_info'

os: 
  - osx
  - linux
  
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env
  # - conda install numpy, scipy, matplotlib, pytest
  - pip install pytest
  - pip install lmfit
  - python setup.py install

script:
  - pytest tests

#after_success:
#  - codecov
#  - chmod u+x deploy.sh
#  - ./deploy.sh
