language: c

python:
  - "3.6"

env:
    global:
    
    env:
    global:
        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test'
        - PIP_DEPENDENCIES='pytest-faulthandler pytest-mpl'
        - EVENT_TYPE='pull_request push'
        - GH_REF: github.com/cmurray-astro/gausspy.git

        # For this package-template, we include examples of Cython modules,
        # so Cython is required for testing. If your package does not include
        # Cython code, you can set CONDA_DEPENDENCIES=''
        - CONDA_DEPENDENCIES='numpy scipy h5py matplotlib'
        # - CONDA_DEPENDENCIES_DOC='sphinx-astropy sip<4.19 Cython scipy h5py matplotlib pytables hdf5 dust_extinction'
        
    matrix:
        # Make sure that egg_info works without dependencies
        - PYTHON_VERSION=2.7 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.5 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.6 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.7 SETUP_CMD='egg_info'

os: 
  - osx
  - linux
  
#before_install:
#  - echo $TRAVIS_OS_NAME
#  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi
#  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then easy_install pip; fi
#  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip install numpy scipy lmfit; fi
#  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip install matplotlib; fi
#  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip install h5py; fi
#  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip install pytest; fi
#  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install python-pip -y; fi
#  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install python-matplotlib -y; fi
#  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install python-h5py -y; fi
#  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo pip install -U scipy numpy lmfit; fi
#  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo pip install pytest; fi


install: 
  - python setup.py install
  # - cat build/bdist.linux-x86_64/egg/lmfit/minimizer.py
  # - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then python setup.py install --user; fi
  # - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python setup.py install; fi

script:
  - pytest tests

#after_success:
#  - codecov
#  - chmod u+x deploy.sh
#  - ./deploy.sh
