# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

sudo: false

env:
    global:
        - SETUP_CMD='test'
        - TEST_CMD='py.test'
        - MAIN_CMD='python setup.py install'
        - PYTHON_VERSION=3.6
        - CONDA_DEPENDENCIES='numpy scipy h5py matplotlib'
        - PIP_DEPENDENCIES='pytest-faulthandler pytest-mpl lmfit'

    matrix:
        - SETUP_CMD='egg_info' TEST_CMD='python --version'
        
os: 
  - osx
  - linux


install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh

  #- pip install lmfit
  - pip install pytest
  - python setup.py install

script:
  - pytest tests  # will run all tests in the package
