language: python

python:
  - "3.6"

env:
    global:
        - GH_REF: github.com/cmurray-astro/gausspy.git
        
# use a virtual environment to install python packages
#virtualenv:
#  system_site_packages: true
      
os: 
  - osx
  - linux
  
before_install:
  - echo $TRAVIS_OS_NAME
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then easy_install pip; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip install numpy scipy lmfit; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip install matplotlib; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip install h5py; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip install pytest; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install python-pip -y; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install python-matplotlib -y; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install python-h5py -y; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo pip install -U scipy numpy lmfit; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo pip install pytest; fi


install: 
    #- cat build/bdist.linux-x86_64/egg/lmfit/minimizer.py
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then python setup.py install --user; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python setup.py install; fi

script:
  - pytest tests

#after_success:
#  - codecov
#  - chmod u+x deploy.sh
#  - ./deploy.sh
